### ISSUE TITLE
Component CRD: Include Gen 5 APIs in YAML specification

### ISSUE THREAD

**Issue by hvaughanattmforum** [tmforum-oda/oda-canvas#128]
## Description

We need to include Gen5 APIs as an alternative in our YAML file specifications.

We see this as changing the API reference in the YAML file to an Array, allowing us to specify as many variants of an API as we need.  We will have to retain Gen4 APIs, as these are still a formally supported TM Forum product.

**Comment by LesterThomas** [comment]
We will create a v1beta3 version of the Component resource and update the specification to allow a list/array or specifications to allow a Golden Component to specify "one of" a list of Open APIs generations.

Do we also want to enable an implemented component to specify multiple versions of a single API (so that a component could offer a Gen5 and Gen4 version of a given API? (any views @sharrop ?)

**Comment by hvaughanattmforum** [comment]
Hi

Yes, we need it both ways.

The Component can pass conformance if it correctly implements one or more of the listed APIs, gen 4 APIs or Gen 5.

So the conformance needs at least one of the APIs in the list, but if there are several alternative APIs listed, each should pass.
