### ISSUE TITLE
operator: Implement Dependent APIs

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#208]
## Description

Implement the custom resources and controllers to implement dependent APIs. We will capture comments and ideas for how to implement dependentAPIs in this issue. The initial comments are from the Innovation Hub workshop on 2024-03-23.

**Comment by LesterThomas** [comment]
The prerequisites for a dependent API are:

The target API must be available and discoverable within the Canvas:
* For APIs on other components within the Canvas, this is automatic - the Component Operator creates an ExposedAPI resource for each API that is available.
* For APIs that are on legacy, on SaaS or on components deployed in a different Canvas, we should create ExposedAPI resources to make these discoverable.

**Comment by LesterThomas** [comment]
There are two high-level features we must support:

1. Explicitly creating the permissions for a user to call an API (this should be against a role that already exists in IDM).
2. Run-time Authentication & Authorization for an API call.

**Comment by LesterThomas** [comment]
The proposal is the component implementation should use a fixed URL for calling dependent APIs (that gets automatically mapped by the canvas to the correct exposedAPI). 
The url will be:
`apiname.component-instance-name.canvas-namespace-name`

i.e. For a `ordercaptureandvalidation` component with a dependency on a `productcatalogmanagement` API, the component implementation assumes the API is at:
`productcatalogmanagement.ordercaptureandvalidation.canvas`

**Comment by LesterThomas** [comment]
Explicitly creating the permissions for a user to call an API: TMF672 User and Permission Management API includes the resources to grant a permission (role) to a user (human or system). 
Question: Is the linking Users to Roles in IDM (e.g. Keycloak) sufficient for this?

**Comment by LesterThomas** [comment]
(These notes should be used to update [Use-case 3](https://github.com/tmforum-oda/oda-canvas/blob/master/usecase-library/UC003-Discover-dependent-APIs-for-Component.md) - this may require re-naming or re-organizing use cases.)
Run-time Authentication & Authorization for an API call:

1. Get access token from Oauth 2 endpoint using client ID & secret. Question as to whether we include scope (i.e. what are we trying to call). Token can be re-used in subsequent API calls (until token expires) - following OAuth standards.
2. Call the API through API Gateway (or Service Mesh) - Gateway will:
* Validate token (authentication) & audience (authorization).
* Map static URL to the upstream URL i.e. from `productcatalogmanagement.ordercaptureandvalidation.canvas` to `r1-productcatalog.component.svc.local/TMF-620/API/`. 
3. Gateway will forward request to upstream implementation (ie. component or off-canvas implementation of the API). *The forward request will replace the token with a token (called last mile security in DT)* specifically for the Gateway for the upstream API being called (this ensures the upstream component can-not impersonate the client component). (This last mile token replacement is not mandatory for MVP - we should have a BDD scenario for this that will initially be pending).
4. Component validates token and enforces authorization (including data authorization).

**Comment by brian-burton** [comment]
> The proposal is the component implementation should use a fixed URL for calling dependent APIs (that gets automatically mapped by the canvas to the correct exposedAPI). The url will be: `apiname.component-instance-name.canvas-namespace-name`
> 
> i.e. For a `ordercaptureandvalidation` component with a dependency on a `productcatalogmanagement` API, the component implementation assumes the API is at: `productcatalogmanagement.ordercaptureandvalidation.canvas`

@LesterThomas , I'm inferring that we do not propose to support multiple similar APIs on the same canvas (e.g. `productcatalogmanagement1` and `productcatalogmanagement2`). Is that correct? I think within a single canvas this is probably OK, but across canvases and during migration between off-canvas and on-canvas APIs there could be multiple of the same API that the component depends on.

The alternative is that we decide that dual-running will be handled by some external logic in the API Gateway or similar.

**Comment by LesterThomas** [comment]
> > The proposal is the component implementation should use a fixed URL for calling dependent APIs (that gets automatically mapped by the canvas to the correct exposedAPI). The url will be: `apiname.component-instance-name.canvas-namespace-name`
> > i.e. For a `ordercaptureandvalidation` component with a dependency on a `productcatalogmanagement` API, the component implementation assumes the API is at: `productcatalogmanagement.ordercaptureandvalidation.canvas`
> 
> @LesterThomas , I'm inferring that we do not propose to support multiple similar APIs on the same canvas (e.g. `productcatalogmanagement1` and `productcatalogmanagement2`). Is that correct? I think within a single canvas this is probably OK, but across canvases and during migration between off-canvas and on-canvas APIs there could be multiple of the same API that the component depends on.
> 
> The alternative is that we decide that dual-running will be handled by some external logic in the API Gateway or similar.

Hi @brian-burton - this pattern should be able to support multiple apis of the same type. e.g. it should be possible for a canvas to have 3 separate product catalogs, to deploy a component with a product catalog dependency, and to grant permission for that component to use one of the 3 catalogs.

**Comment by pecanpete** [comment]
Do We need versioning on dependent APIs so we can do A/B testing ?

**Comment by ferenc-hechler** [comment]
Some thoughts from my side:

The initial setup is quite similar to the Component-Vault approach, where we added a new structure in the security functions which has to be extracted into an own custom resource by the ComponentOperator:

![Component Operator Extraction](https://raw.githubusercontent.com/ODA-CANVAS-FORK/oda-canvas-component-vault/master/source/operators/componentOperator/sequenceDiagrams/componentOperator.png)

So, instead of extracting the componentVault section in this use case the dependentAPI sections have to be extracted.

The ComponentOperator then watches the status of each newly created dependantAPI custom resource until all went into status READY (maybe there are optional ones, which do not have to be READY for the component to be functional).

The whole magic behind happens in the DependantAPiOperator, which process each of the extracted DependentAPI custom resources. The advantage of this decoupling is, that the ComponentOperator does not have to know about HOW the DependentAPIOperator is doing its job and works independently of the specific implementation. 
So, there can be an simple implementation, which only knows about the locally exposed APIs in the own Kubernetes cluster. Another Implementation could support legacy APIs and a third one could be multi-cluster aware.

The good thing is, we can start in the reference implementation we the simplest one but still have the ability to support more complex scenarios.

What I have in mind is managing an ODA Registry outside of the Kubernetes cluster and the DependantAPIOperator would lookup the endpoints in this central registry:

![image](https://github.com/tmforum-oda/oda-canvas/assets/11094156/ce6b6b78-e9a9-47dc-a722-3ce1f0e8ad83)

But to allow this functionality we will need to be able to provide additional info in the dependentAPI entry.

This could be be a generic key-value selector like for Kubernetes "labels". So, we could add selectors for the release name, the namespace, the cluster, the application, the development-team, the organization-unit, ...  
At the moment our only selector is the OpenAPI specification, which might not be unique, as @brian-burton mentioned above.
But combining the OpenAPI spec with a release name might be unique.

Of course I have our DT workflow in mind. Each OpenAPI is published in a central registry by a Team and other applications have to "subscribe" for a published API to be able to use it. There is an approval workflow, which is partly automated. For example subscriptions can be auto-approved, if requester and provider are from the same Team.

The endpoints returned by the API Gateway does not directly point to the published API, instead of it directs to the API Gateway, which handles the M2M Authentication and Authorization. The API itself only verifies the Last-Mile security from the API-Gateway:

![image](https://github.com/tmforum-oda/oda-canvas/assets/11094156/c2637b8d-b6a0-4555-a825-f33c41f43d70)

Each subscriber gets its own Client-ID & Client-Secret, so that each communication relation can be identified. 
I don´t want to push this solution into the reference implementation, but I want to keep the solution flexible, so, that this workflow is compliant with our Canvas implementation.   :-)


The DependantAPIOperator is responsible for configuring the API Gateway to allow communication between two components.
This means, the consuming ODA Component has to "retrieve" the endpoint URL and eventually Client-ID & -Secret. 
How can this be achieved? 
The URL could be stored in a ConfigMap and Client-ID & -Secret in a Kubernetes Secret and the Deployment could be "patched" to inject those values.
For the ComponentVault we are injecting a tiny local SideCar, with which is reachable via localhost and the sidecar knows about the details how to communicate with the Component Vault. This could also be done with the outgoing communication.

...

maybe worth an own session to discuss this topic in more detail

**Comment by LesterThomas** [comment]
@ferenc-hechler - when we initially install an ODA Component, we create a system user for that component in keycloak (to be used by the component for subsequent outbound API calls). Do you have a view to how we pass the client_id and secret for this system user into the component?

**Comment by pecanpete** [comment]
Observation on the idea of the dependant API controller . The more i look at this the better the idea seems . We do something similar with an API gateway on the ingress side so sound pretty neat to do something similar on the egress side  By chance I saw this in a IFP post at https://www.insightsforprofessionals.com/en-us/it/security/7-easily-exploited-cloud-misconfigurations/download
**Unrestricted Outbound Access**
This cloud setting misconfiguration allows for unrestricted communications from internal assets, 
opening the door for outbound adversary communications and data exfiltration. 
Also described as free network egress, unrestricted outbound access is a misconfiguration in which 
cloud resources like containers, hosts and functions are allowed to communicate externally to any 
server on the internet, with limited controls or oversight. This can be a default misconfiguration, and 
security teams often have to collaborate with counterparts in IT or DevOps to meet certain security 
standards.
Because developers or system owners don’t always have full knowledge of the various external services 
that a workload might depend on, and because they might be accustomed to having unrestricted 
outbound access in their other work environments, some organizations battle with trying to close this 
loophole.
**How This Is Exploited by Adversaries**
Wherever untrusted data is processed by a workload — for example, a web request, a message in a 
queue, or a file uploaded to a service — an adversary can try to compromise the underlying software 
processing that data, an attack method called remote code execution, followed by payload retrieval or 
establishing a reverse shell. If outbound access is not permitted, such attacks cannot land. By default, 
however, once the adversary’s initial code execution attack succeeds, they have complete execution 
control in the environment

**Comment by ferenc-hechler** [comment]
> @ferenc-hechler - when we initially install an ODA Component, we create a system user for that component in keycloak (to be used by the component for subsequent outbound API calls). Do you have a view to how we pass the client_id and secret for this system user into the component?

The most simple idea which comes into my mind is to create a Kubernetes secret and patch the deployment to inject this as ENV variables. This solution is not optimal from the security perspective. 

As an alternative we could use the ComponentVault to store the secrets, so that the service can get client-id and secret from its own ComponentVault.

Another solution would be to totally decouple authentication/authorization from the ODA components core functionality by using a sidecar which handles all the oauth2 part of the communication. We discussed this internally in DT and Marcus Greuel liked this idea very much. It would also resolve @pecanpete concernes about unlimited egress (PODs can be restricted, only the sidecar knows how to get out of the cluster). 

This could also be modified to setup a local trusted zone (maybe on namespace or cluster level) with one central egress service which could be used instead of the sidecar. 

As we try to be as flexible as possible, this could also be a part of the dependentAPI/component configuration, how dependent APIs are thought to be accessed. 

```
    dependentAPIs: 
    - name: party 
      apitype: openapi     
      access: sidecar
      sidecar:
        port: 5001
      specification: https://open-api.tmforum.org/TMF632-Party-v4.0.0.swagger.json  
```

or 

```
      access: k8sSecret
      k8sSecret:
        clientIdEnvName: CLIENT_ID
        clientIdEnvName: CLIENT_SECRET
```

or 

```
      access: localGateway
      localGateway:
        urlEnvName: LOCAL_GATEWAY_URL
```

**Comment by pecanpete** [comment]
Additional thoughts which might help select preferred option. The  starting point for this discussion was deploying and configuring an individual component. 
Thinking our aloud to seek others opinions When we have talked about Zero trust one naturally thinks of the trust/threat boundary being an individual component. I am wondering if we need to consider Security by design and operations
However several catalysis have shown that typically a component sits with several other behind and PI gateway where the components trust each other and the security domain/ trust boundary is essentially the zero trust boundary.
Could we think of deploying a component into a security domain which has both ingress and egress controls? then the questions are where the policy decision point is and where the policy enforcement points are  ( the later are probably the API gateways and the Dependant API Controller which is like a reverse API gateway . Now the degenerate case is one Component per Security domain but more likely that several component will be with a security domain .. 
So would the general case be to deploy a component into a security domain ( probably needs a namespace ).  This changes thinking from solely one component per domain  to be be more general. Thoughts . May be we need a security Doman controller to which component can be added and removed and provides that mapping between security decision points asn security enforcement points . One could also add systems wide policies rather than solely per component policies such as GDPR. IN this approach the dependant API controller would also resolve the API name to either internal or external components  to a security domains.  Opinions? Better ideas?

**Comment by LesterThomas** [comment]
> Another solution would be to totally decouple authentication/authorization from the ODA components core functionality by using a sidecar which handles all the oauth2 part of the communication. We discussed this internally in DT and Marcus Greuel liked this idea very much. It would also resolve @pecanpete concernes about unlimited egress (PODs can be restricted, only the sidecar knows how to get out of the cluster).

I like this concept. We would probably need to make the sidecar an optional implementation of the dependent API authentication (and allow components that implement their own approach). For the concern about limiting egress - this can be achieved using the Egress Gateway of the service mesh.

**Comment by pecanpete** [comment]
So presumably the installation of the component should trigger configuration of the  the Service mesh . Think there is still some value in having a explicit controller to do all of this separate from the Lifecycle manager. An the point about being explicit as to where policy decision and enforcement point  are should be address at some point. ANd maybe for K8s we need to document as decision as to where the security domains are .eg. could be PODs

**Comment by bradspau** [comment]
One of the options is definitely to utilise OAuth and use the access token for accessing the resources post authentication/authorisation. You could also pass the claims between the components and implement a fine-grained access control mechanism. Using this mechanism, you can also have another component that manages the overall user behaviour and establishes the concept of trust on a continuous monitoring basis (behaviour monitoring of the service account). If the behaviour changes, then you can deny the claims when the component performs introspection.

Using ENV variables is not very secure, similar to using Kubernetes secrets. The later are just base64 encoded and anyone that gains access to a pod can easily decode the secret, recover it and then use to gain access potentially moving laterally (depending upon what the secret is used for). The prior is similar if a terminal session on the container is executed then they can easily discover the secret.  

The better way of dealing with the secrets is to use an external vault that is more secure, and components recover secrets on demand. If you want to provide even greater protection for the secret, you can pair the vault with a hardware security module such that they cannot be tampered with. External Secrets Operator with Kubernetes enables easy integration possibly.

**Comment by AliSaygin** [comment]
Hi,
We have a proposal to extend the current Component CRD. Our initial requirement is to validate and allow the processing of the requests made to a component whose payload is having a reference to a resource/entity managed by a dependent API server known by the component.
In a formal way, requirement description is:

- If a component;

  - receives a request (http POST, PATCH etc.) on an endpoint and

  - the request payload has a  “**_`#72528A`href_**” attribute which refers to a dependent API resource

     Then;

  - the ‘**Base URL**’ of the “href” attribute should be validated if the target is allowed or not.

- There could be multiple dependent resource references in payload. Each one needs to be validated without checking if it’s mandatory or not.

- Optionally,

  The payload may not have direct reference to the dependent resource. The reference is inferred during execution.

### The diagram below depicts a sample use case:
![Presentation1](https://github.com/tmforum-oda/oda-canvas/assets/142574880/d8050c55-5ae7-4a6a-ba33-5ab4e8e640aa)



- Product Inventory Management Component is integrated with 2 TMF620 - Catalog Implementations provided by various vendors.
- The dependent API may not be a TMF Component.
- The access to dependent API server resources might be protected by any type of authorization server.
- The “**_href_**” attribute in message payload must refer to a resource maintained in one of the Dependent API server.

The changes we proposed are depicted in the “TO BE” slide color coded.
![Slide4](https://github.com/tmforum-oda/oda-canvas/assets/142574880/028b0a78-f72e-4d1c-945b-be300edb621b)

![Slide5](https://github.com/tmforum-oda/oda-canvas/assets/142574880/1126abac-801f-4051-8185-94a7fa73cc9f)

![Slide6](https://github.com/tmforum-oda/oda-canvas/assets/142574880/16534cd2-4aee-4e9c-a86e-4a3a61ef4d89)

I'll explain the details of each feature in separate messages.

**Comment by AliSaygin** [comment]
# Feature#1
## **Motivation:**

- The request payloads may have references to the dependent API endpoints. To limit the component to communicate with the allowed dependent APIs, their details should be stored in a resource and be readable by the component to validate access.

- The “**_dependentAPIs_**” object type in “_Component_” CRD is not capable to hold the required data.

## **Enhancement proposal:**

* “**_openAPIV3Schema_**” object could be extended to have the necessary attributes in this draft schema snippet. 

* ”**_dependentAPIs_**” could be extended to hold extra data regarding to the exposing services

![Capture1](https://github.com/tmforum-oda/oda-canvas/assets/142574880/0b645b39-94ce-4469-9b6e-fcabff963422)
![Capture2](https://github.com/tmforum-oda/oda-canvas/assets/142574880/0178076e-8479-4c11-8a70-a45a4a259f71)

The above data will be used to compose a Base URL which will be used to validate the resource references, like _href_, in payload.

**Comment by AliSaygin** [comment]
# Feature#2

## **Motivation:**
The dependent APIs’ contract document location should be defined per provider and accessible to the component.  

## **Enhancement Proposal:**
  The "**_specification_**" attribute under _**"dependentAPIs"**_ should be moved under _"providers"_ and be **_mandatory_**. 

![Capture-3](https://github.com/tmforum-oda/oda-canvas/assets/142574880/0b829dda-0dbd-46ac-a779-413e7820e828)

**Comment by AliSaygin** [comment]
# Feature#3

## **Motivation:**
HTTPS protocol requires TLS/SSL certificates to be exchanged to start a communication. The ODA Component needs to have the dependent APIs TLS certificate provided by a K8s resource or a service. The current schema doesn’t support to access it.

## **Enhancement Proposal:**

- The target service's certificate should be stored in a K8s resource and there should be an attribute that could hold a reference to it. 
- As an option, a canvas function can be used to get & renew Certs.
- An Individual ODA Component serving centralized Certificate Management functionality as Security Function.

![Capture-4](https://github.com/tmforum-oda/oda-canvas/assets/142574880/f95c741a-7614-47db-ade6-ae0f9532c86a)

**Comment by AliSaygin** [comment]
# Feature#4
## **Motivation:**

- The "**_apiType_**" attribute in "**_dependentAPIs_**" should not be limited with "**openapi**" enum type. Those endpoints may not support Open API contracts.

- It should be capable to qualify other types of APIs.

## **Enhancement Proposal:**

- The "**_apiType_**" attribute in "**_dependentAPIs_**" is extended to keep other APIs that are not Open API compliant.

![Capture-5](https://github.com/tmforum-oda/oda-canvas/assets/142574880/d8db63eb-9786-47e2-b20e-3fb9c75ab237)

**Comment by AliSaygin** [comment]
# Feature#5

## **Motivation:**

- The dependent APIs may require access authorization. This may require communicating with an authorization server to get an access token or some other way for authorization. These details couldn’t be stored in the current schema.

- The “**_coreFunction.dependentAPIs_**” needs to be associated with "**_securityFunction.dependentAPIs_**“ by having a reference to them.

![Capture-6](https://github.com/tmforum-oda/oda-canvas/assets/142574880/3e7d9626-97bb-4a21-a4b7-d9e9fcd3ec61)
                               Sample authorization request params

## **Enhancement Proposal#5.1:**

- In the above use case, consuming vendor1 catalogue API requires communicating with the _OAuth/OIDC_ endpoint to get a token. This call requires some mandatory parameters as below to be provided. 

- These authorization request data could be stored in a **K8s Secret** object or an _alternate security service_. The reference to this object can be held in an attribute “**_tokenRequestSecretRef_**” under the “**_securityFunction.dependentAPIs_**” like below.

![Capture-7](https://github.com/tmforum-oda/oda-canvas/assets/142574880/ac03448f-6333-40bd-b5ae-cf6daae40289)

## **Enhancement Proposal#5.2:**

- The authorization service reference is responsible for issuing tokens and controlling access to “**_coreFunction.dependentAPIs_**” element associated with it. 

- The “**_authzService_**” refers to a valid element in the “**_securityFunction.dependentAPIs_**” list.

![Capture-8](https://github.com/tmforum-oda/oda-canvas/assets/142574880/b853fe2e-5fc5-42d7-b43f-9658443ff5cc)

**Comment by LesterThomas** [comment]
@AliSaygin - where you add a `providers` section to the Component specification, where does this data come from? Is it defined by the Component Vendor, or is it specified in the values.yaml file or the helm chart (by the CSP or automatically by one of the operators), or somewhere else?

**Comment by ferenc-hechler** [comment]
About Feature #1 "Dependent API Provider/Implementation"

> Motivation 1:
> The request payloads may have references to the dependent API endpoints. 
> To limit the component to communicate with the allowed dependent APIs, 
> their details should be stored in a resource and be readable by the component to validate access.

A component requests access to a number of dependent APIs.
Every requested dependent API needs to be resolved to a set of communication parameters, which have to be made available to the consuming component. The most obvious communication parameter is the endpoint (URL) but there are other communication parameters which might be necessary for authentication/authorization like client credentials for an OAuth 2.0 workflow.

> Motivation 2:
> The “dependentAPIs” object type in “Component” CRD is not capable to hold the required data.

The component CRD is not the place to hold the communication parameters. Here the demand to access an API is requested on the logical level. Our current concept is to create own DependentAPI custom resources for each requested dependent API (in the same way as it already works for exposed APIs). And the CRD of the DependetAPI can hold the communication parameters. For the endpoint this is not a problem, but for the credentials we need another way how to transfer them to the consuming component.

Also, having the communication parameters stored in the DependentAPI custom resource does not make them directly accessible inside the component. I don´t expect the components to read and parse the custom resources. Instead of the data can be injected into k8s configmaps and secrets and injected into environment variables or filesystem. For the credentials we could also use the component vault of the SecretsManager: The canvas stores the credentials into the vault (password safe) of a component, from where the component can read the secrets in a secure manner.

About the not so critical endpoints I could also think about a canvas-information endpoint, which is accessible for components. This endpoint could be used to query information from the canvas, like the version number and the capabilities. 
It could also be used to query communication parameters for a dependent API. Each dependent API requested by a component has a unique name, e.g. "party". So the component could ask the canvas-info for the communication parameters using the name of the dependet API: 

```
  canvasinfo.getCommunicationParameters("ctk-productcatalog", "party")
```

The reponse can be positive, negative or pending, based on the state of the Dependent API custom resource.
Having an OpenAPI canvasinfo endpoint accessible inside the cluster would solve the Component->Canvas communication, which otherwise has to be resolved in every use-case. For example the IdentityConfiguration defines a fixed name for an cluster internal endpoint and the SecretManager uses a sidecar to have a localhost communication.

**Comment by pecanpete** [comment]
folks at last week's ODA Canvas workshop some similar topics to Feature #3 and #5 were discussed.
We reviewed this Github discussion  on the ODA Security team today and Ali Saygin presented the background and options.
ODA team would like to proposal a workshop in a couple of weeks to address Feature #3 and #5 . The thinking was we need some integration  pattern defined  for how multiple ODA component securely  interact . There are other input namely   [V](https://www.tmforum.org/resources/introductory-guide/ig1330-oda-technical-capability-identity-and-access-management-iam-stage-1-and-2-v1-1-1/) ; some input on added Zero trust to Legacy applications and some ideas about information security. 
My proposal is to put up an agenda on Friday this week  for review and discussion.

**Comment by AliSaygin** [comment]
> @AliSaygin - where you add a `providers` section to the Component specification, where does this data come from? Is it defined by the Component Vendor, or is it specified in the values.yaml file or the helm chart (by the CSP or automatically by one of the operators), or somewhere else?

`providers` data can be supplied via Component.yaml and/or values.yaml, the providers list can be defined depending on the APIs to be integrated at deployment time. But we can have an open discussion to evaluate all the alternative ways.

**Comment by LesterThomas** [comment]
Here is my attempt at a summary of the discussion above, with an objective of making a decision as what to do next:

For the dependent API management, the declaration of the dependencies is in the Component custom resource (and synchronized into individual DependentAPI custom resource to be processed by a Dependent API Operator). 

 There are multiple options for how the component software discovers the providers for these dependencies. I have outlined 4 options with a discussion of the pros & cons. Feel free to comment further!

| Option                                               | Pros & Cons                                             |
| --------------------------------------- | -------------------------------------------- |
| DNS - the Dependent API Operator creates a DNS entry for each dependency and the component software calls this DNS.  | This is a simple solution, but I'm not sure how we would handle a list of providers for a single dependency. Also, the component wouldn't know if there were zero providers for an API, or if the providers just were not ready |
| Canvas.Info API - the Canvas provides a standard API endpoint for the component to call to discover API providers. This would probably be a Service Inventory API call. | The Canvas.Info option could support multiple providers for each dependency and also show the ready status for each provider. The Canvas.Info could be used for other services to integrate data into the component. |
| ConfigMap - the Canvas creates a configmap for each dependent API. The Components Pod;s can read these as environment variables. | There are some issues to handle updating of configmaps (as Pods will require restarting). |
| Provider details in Component CRD - This option is to add the provider details into the Component custom resource. This enables deployment-time configuration of any API providers. | From a security perspective we didn't want to provide the raised privileges for a component to call the Kubernetes API. |

**Comment by LesterThomas** [comment]
Please indicate your preferred option or any other comment on this decision. My preference is for the **Canvas.Info** API option, but I am also open to other perspectives.

**Comment by brian-burton** [comment]
I prefer the canvas info API and I agree that the [Service Inventory API](https://www.tmforum.org/resources/standard/tmf638-service-inventory-api-user-guide-v5-0-0/) would be a good idea. This fits with the Kubernetes operating model as well. We can publish a known service inventory endpoint that's the same in every Canvas, then when a component registers its dependent APIs via the Canvas CRDs it can then check the inventory for those dependent APIs to be populated in the inventory before deployment is complete.

**Comment by LesterThomas** [comment]
To implement this decision using **Canvas.Info API**, I have created some sub-issues:

* Build Canvas.Info microservice that implements the [Service Inventory API](https://www.tmforum.org/resources/standard/tmf638-service-inventory-api-user-guide-v5-0-0/) and returns to the component client the list of dependent API services that are available for it to call. Documented as issue #289 
* Build example component to use for testing. Documented as [reference-example-components issue 18](https://github.com/tmforum-oda/reference-example-components/issues/18).
* Build BDD features and scenarios to test the Dependent APIs. Documented as issue #290
*

**Comment by LesterThomas** [comment]
The simple Dependent APIs are complete and working. There are some proposed enhancements in #384
