### ISSUE TITLE
Docs: Update use-case and feature naming to reflect Canvas Operators from DTW-Asia

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#211]
## Description

During Innovation Hub week and DTA Asia, we updated the naming of the Canvas Operators to the picture below

![image](https://github.com/tmforum-oda/oda-canvas/assets/7374014/27fc99ac-f629-4766-b42e-7b45d82378ec)

This issue is to update the Canvas Operator names  to reflect this (and also re-visit the use case names and feature names, if necessary)

**Comment by pecanpete** [comment]
Need to add ODA Component Lifecycle Management

**Comment by pecanpete** [comment]
BDD Use case naming conventions at https://github.com/tmforum-oda/oda-canvas/blob/211-docs-update-use-case-and-feature-naming-to-reflect-canvas-operators-from-dtw-asia/usecase-library/use-case-naming-conventions.md 
 Doccuemtn is currently Is actually BDD guidelines not Feature naming guidelines 
We do have on confluence a BDD Guidelines document evolved  over last year since Accelerate workshop 2023  on confluence at https://projects.tmforum.org/wiki/display/TAC/ODA+++Behaviour+Driven+Design%28BDD%29+Feature+Guidelines  . 
Should we combine this material with this and publish on GitHub rather than confluence? 
Note this document does have  some name convention for organising and naming features in ref 5 https://cucumber.io/blog/bdd/solving-how-to-organise-feature-files/
