### ISSUE TITLE
operator: the keycloak identity operator registers for role updates twice

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#230]
## Description

The [keycloak identity operator](https://github.com/tmforum-oda/oda-canvas/tree/master/source/operators/securityController) registers with the partyRole API for each component that is deployed - this is the expected behaviour.

The issue is that the securityController appears to registers to each component twice! If you query the `Hub` resource of this partyRole API, you can see the listeners that have registered. For the example component you will see:

```
[
  {
    "callback": "http://seccon.canvas:5000/listener",
    "id": "ffb1b051-e8d5-4198-b0cd-ffcfe702ce16"
  },
  {
    "callback": "http://seccon.canvas:5000/listener",
    "id": "c61b8f3a-b41b-4a27-ba4a-8d781cb8521d"
  }
]
```

i.e. it seems to have registered twice.

**Comment by adarshkumar4** [comment]
When a component is installed on canvas, securityController software makes post request to partyRole API hub endpoint to register a listener which is the expected behaviour. 

But whenever a component is installed on canvas, partyRole API is making that post request to hub endpoint twice which can be seen in partyRole API logs screenshot. It's happening for some unidentified reason and there is no error in logs also to justify it. 
![Screenshot 2024-09-03 161707](https://github.com/user-attachments/assets/4cefd684-7331-4d05-a50a-d0143dbd37a3)
![Screenshot 2024-09-03 161725](https://github.com/user-attachments/assets/fbae5681-e97f-494b-a68c-fda7f6183c34)

If we are deleting one of the two registered listeners during component installation, then deleted one is not appearing when component Istio controller pod is restarted, and remaining listener is working properly.   
After component got installed on canvas, whenever we are trying to register partyRole API listener it is registering for once only.

**Comment by adarshkumar4** [comment]
After adding a log message before the function which registers a listener for API. It's seen in logs that function to register a listener is called for three times during the installation of a component on canvas as the whole of this function is called on resource update and it updates for multiple times during installation of a component.

Out of these three times only two times listener is successfully registered and failed for once may be due to the exception for which I have raised this [issue](https://github.com/tmforum-oda/reference-example-components/issues/27) in [reference-example-components](https://github.com/tmforum-oda/reference-example-components) repo.

To prevent this error, added a condition that calls the function to register a listener only if it's not registered.
