### ISSUE TITLE
operator: DependentAPI name is prefixed with dapi-

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#302]
## Description

This is a small issue with the naming of the DependentAPI created from the component. For the ExposedAPI, the name of the ExposedAPI is `<release>-<componentname>-<exposedapiname>`

For the DependentAPI, it has an additional prefix of `dapi` which I think is unnecessary and doesn't follow the pattern (it is unnecessary since we know it is of Kind DependentAPI).

**Comment by ferenc-hechler** [comment]
I will start working on this issue, as soon as the PR #295 (automate docker build) is merged, because the changes require an updated docker image.

**Comment by ferenc-hechler** [comment]
I deployed the productcatalog component with a shorter release name "dapit" and now the deployment was successful.
Looking at the generated custom resource:

```
$ kubectl get dependentapis -n components

  NAME                                                           DEPAPI_ENDPOINT                                                                                            DEPAPI_READY
  dapit-productcatalogmanagement-dapi-downstreamproductcatalog   http://components.ihc-dt.cluster-3.de/alice-productcatalogmanagement/tmf-api/productCatalogManagement/v4   true
```

So, "dapi" it is not a prefix it is an infix to separate the component-name from the dependent-api name.

```
dapit-productcatalogmanagement-dapi-downstreamproductcatalog
<release>-<component>-dapi-<dependencyname>
```

It was thought to avoid name-clashes if <component> and <dependencyname> also contain "-" characters.

I must admit this is not very likely, but it is possible to create name clashes on purpose.
With normal naming rules it should not happen.

One example for a name-clash:

release | component | depndencyname | custom resource name 
--- | --- | --- | ---
abcrel | comp1-summer | party | abcrel-comp1-summer-party 
abcrel | comp1 | summer-party | abcrel-comp1-summer-party|

**Comment by ferenc-hechler** [comment]
The relevant piece of code:

https://github.com/tmforum-oda/oda-canvas/blob/82091fa04ed383296861a7f0c37f198cf57487da/source/operators/componentOperator/componentOperator.py#L448

```
@kopf.on.resume(GROUP, VERSION, COMPONENTS_PLURAL, retries=5)
@kopf.on.create(GROUP, VERSION, COMPONENTS_PLURAL, retries=5)
@kopf.on.update(GROUP, VERSION, COMPONENTS_PLURAL, retries=5)
async def coreDependentAPIs(meta, spec, status, body, namespace, labels, name, **kwargs):
    ...
    dapi_base_name = f"{name}-dapi"
    ...
```

Changing this to `dapi_base_name = name` might fix the issue.
But we have to check for if there exist other dependencies to the naming convention.

**Comment by ferenc-hechler** [comment]
This issue is a perfect example, how the new Docker build process works:

https://github.com/tmforum-oda/oda-canvas/pull/305/files

![image](https://github.com/user-attachments/assets/e7e30972-08af-41b9-bc1e-af765bff4800)

Step | Description |
--- | ---
1 | Increment the version number of the dockerfile to change and set the prereleaseSuffix, e.g the issue number
2 | change the source code. This triggers the docker build of the prerelease version
3 | adjust the tests to test the changed code (steps 2 and 3 iterate multiple times)
4 | prepare everything for the Pull-Request, set chart-version numbers, document changes, also update the version number in the dependent chart, which uses the dockerfile
PR | create Pull-Request -> BDD Tests are executed and should be successfull 
5 | before merging, remove the prereleaseSuffix. This will make the check for no-prerelease-suffixes green
Merge | this triggers the build of the release docker images
