### ISSUE TITLE
operator: Standardize and improve logging

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#320]
## Description

The ODA Canvas software operators (described in [usecase-library#oda-software-operators](https://github.com/tmforum-oda/oda-canvas/tree/master/usecase-library#oda-software-operators) ) each create logging data. This issue is to normalise this logging data to simplify troubleshooting. There is a utility at  [canvas-log-viewer](https://github.com/tmforum-oda/oda-canvas/tree/master/source/utilities/canvas-log-viewer) that visualizes the log data, grouping the logging information by `kubernetes resource`/`operator`/`handler` to help with troubleshooting.

The example output looks like:

![canvas log](https://raw.githubusercontent.com/tmforum-oda/oda-canvas/master/source/utilities/canvas-log-viewer/canvas-log-viewer.png)

For the python/kopf operators, I propose we standardize using the example logWrapper in the ComponentOperator:

https://github.com/tmforum-oda/oda-canvas/blob/e527bd0456679259f0b6d38045c411ff1ada8fee/source/operators/componentOperator/componentOperator.py#L1499-L1515

For the other operators, we should create an equivalent function that generates the same output.

**Comment by ferenc-hechler** [comment]
The refactoring was not that simple, because the information available in the handler method itself is not available in the methods called from there. So to call the method logWrapper() with the correct infos for handlerName, componentName, resourceName it is neccessary to hand over all this variables from the handler to the method called. And if this method calls another method which uses logging again all variables have to be added.

Instead of I introduced a Class LogWrapper, which remembers those variables. So instead of adding all three variables to the signature the LogWrapper instance can be added to the signature.

Additionally a decorator `@logwrapper` was added to create a copy of the LogWraper instance (to not change the calling instance) and automatically set the functionname.

https://github.com/tmforum-oda/oda-canvas/blob/f3006d44e5c05d209eb82b1fcddc9e09c75ec212/source/operators/secretsmanagementOperator-hc/docker/log_wrapper.py#L10

```
def xyzHandler(params):
    logw = LogWrapper(handler_name="xyzHandler", function_name="xyzHandler")
    logw.info("entered xyz")
    abcMethod(logw, params)
    ...

@logwrapper
def abcMethod(logw, params):
    logw.debug("entered abcMethod", params)
    ...
```

in abcMethod, the logw instance has handler_name "xyzHandler" and function_name "abcMethod" automatically filled from the decorator.

**Comment by ferenc-hechler** [comment]
SecretsManagement-Operator and DependentAPI-Simple-Operator use the new LogWrapper class and can be parsed by the Canvas Log Viewer:

![Screenshot 2024-11-18 090614](https://github.com/user-attachments/assets/f55b703b-a457-4672-a71b-033d9840577d)

**Comment by ferenc-hechler** [comment]
PR #400 was merged.
SecretsManagement-Operator and SimpleDepedentAPIOperator now support the log format required for Canvas Log Viewer.
