### ISSUE TITLE
Feedback on Authentication use-cases: UC1, 2, 3, 7 & 8

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#62]
## Description

Please use this issue thread to capture any feedback on the Authentication use-cases:
* [UC001-Bootstrap-role-for-component](https://github.com/tmforum-oda/oda-canvas-charts/blob/master/usecase-library/UC001-Bootstrap-role-for-component.md)
* [UC002-Expose-APIs-for-Component](https://github.com/tmforum-oda/oda-canvas-charts/blob/master/usecase-library/UC002-Expose-APIs-for-Component.md)
* [UC003-Discover-dependent-APIs-for-Component](https://github.com/tmforum-oda/oda-canvas-charts/blob/master/usecase-library/UC003-Discover-dependent-APIs-for-Component.md)
* [UC007-Authentication-external](https://github.com/tmforum-oda/oda-canvas-charts/blob/master/usecase-library/UC007-Authentication-external.md)
* [UC008-Authentication-internal](https://github.com/tmforum-oda/oda-canvas-charts/blob/master/usecase-library/UC008-Authentication-internal.md)

**Comment by peeterko2** [comment]
On UC007:

1. The proposed flow makes the API gateway responsible for checking the validity of the token. The component itself doesn't check the validity of the token. I am under the impression that this is a violation of the 'zero-trust' principle. A component should not trust a token that was not validated by the component itself.
2. ODA will need to support both system-user based scenarios and human user based scenarios. It is quite obvious that when a ProductOrderManagement component updates a ProductInventory component, no human user is involved. When a webGUI is used to update a customer record the situation is more complex. The webapplication is probably allowed to update customer records. But that is not necessarily the case for every user of that application. Also here we seem to be violating the zero-trust principle. Even if a human user is allowed to make the update, the PartyManagment component will want to know which Human-User made the change so that this information is available for auditing purposes.
3. The flow should also specify that when a valid token is provided but it doesn't contain the appropriate role the response should be 403 Forbidden.

**Comment by peeterko2** [comment]
On UC008:

1. Just like UC007 this use case will also require an access management flow. Permission should be given by assigning the role to the system user. There is potentially scope for more automation. The distribution of key could potentially be handled by an operator.
2. Also in this use case a human-user based scenario is possible. One of the components might provide a user interface used by humans. In that case a passthrough seems not unlogical.

**Comment by peeterko2** [comment]
On UC001:

1. Based on previous discussions the flow should probably use TMF672 UserRole instead of TMF669 PartyRole.
2. Currently the User "seccon" is created in "myrealm". Is it not better to create a less generic realm like "oda" or "canvas"

**Comment by brian-burton** [comment]
For UC007, we mention pass-through authorisation. We need to expand that so that the concept is understood. Broadly there are two models we could use, and we are proposing to prove out the first:

1. Every system checks that their users are authorised to perform an action and no user information is passed through to another system. This means that, for example, a customer accessing their account information via an API or portal is authorised by that front end to access both the front end itself and information related to their account. Any request to a back end system that is not related to their account will not be attempted by the front end. In turn, the front end has access to many customer accounts, and therefore the front end has broad access authorisation to the back end. This is a simple model, but places quite a heavy burden of trustworthy authorisation with individual systems.
2. Every system passes user information to other systems for those systems to perform their own authorisation checks. This means that, for example, a customer accessing their account information via an API or portal is authorised by that front end to access the front end only, and when requests to the back end are made details of the user are passed through so that the back end can perform its own authorisation checks on both the front end and the user. Any request to a back end system that is not related to their account may still be passed by the front end, but the back end will refuse the request on the basis that although the front end is authorised to make the request the actual customer is not authorised to see the information requested. This model is more complex: as an example, it requires all systems to know of all possible users and has the potential to overload the identity management platform with repeated requests for authorisation verification from multiple systems for the same request.

**Comment by gjo-satec** [comment]
On UC001
Secrets - Identity

- Create and assign a role specifically to access the secret for the deployment/statefulset
-  Mutating operator for dynamically adding the secret.
-  Rotate Secrets
-  If aiming for zero security we should aim for encryption at [rest ]( https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#ensure-all-secrets-are-encrypted)or even the use of Vaults

We need to clarify terms In my understanding, a role in a component may be more like a Permission, mainly about their exposed business API, along with supplemental APIs like security and configuration. Permissions are allowances for performing different operations on the resources exposed by the APIs, such as read (GET), create (POST), update (PATCH), etc. These permissions may need to be defined in advance.

I don't aim to have roles defined in the component. I don't think there's such a thing as an administrator of TMSC001; that concept has no business meaning tome. It's up to the Enterprise to decide its roles based on internal business processes. Typically, these roles will be composed of several permissions across many components. Usually, an identity will be associated with one or more of these roles. However, these roles should be managed in the IDM in a centralized manner, among other things, for security auditing.

**Comment by gjo-satec** [comment]
On UC003
Agree on not allowing components to query dependencies. 
Maybe even check in with the operator if any permission is requested on installation
Said that the manual solution proposed poses too many burdens to operation.
1.- It's a manual process in a dynamic components landscape.
2.- Timing became important. Once you deploy a component you have to update the dependent ones...
3.- How does Ops know what to update? We are talking about a spreadsheet? Many components may have a dependency on a third component. Forgotten one can lead to loss of service

A more ops friendly will be to declare the dependencies with "preferences" in the form of labels (e.g oda.tmforum/vendor, oda.tmforum/api, and so)  and let the operator fulfil that, based on those intends , and inject a config map with the resolved dependencies

**Comment by gjo-satec** [comment]
On UC007
The use case described requires maintaining n-credential pairs, corresponding to the number of dependent API calls needed. Same need than UC001 but multiply

Internal calls should only occur as part of the process required by an externally exposed API.
Once an external call made by an individual user (Identity) is authorized, all other necessary permissions should be granted automatically. For example, if a user has the right to create a Service Order, all related internal calls should be authorized regardless of the number or chain of components involved (e.g., component A depends on component B, which depends on component C). This process may be asynchronous.

To enhance security, we can implement measures like mutual TLS (mTLS) and network policies to restrict access to allowed systems only. Assigning roles to internal components may make the system fragile, as changes to an internal role could disrupt the authorization process.

Using mTLS authentication and a set of network policies, we can allow call flows only between authorized systems. 
In some cases, pass-through authorization might be necessary, perhaps for regulatory compliance. However, this approach can be challenging, especially when defining roles and permissions in Identity and Access Management (IAM). Security teams need to know not only which role to assign but also the implications of that role, including any associated third-party roles/permissions. This level of technical knowledge may be beyond the scope of security personnel.

**Comment by gjo-satec** [comment]
On UC007
the concept of having a system role for a website may not be entirely clear. Additionally, implementing a Client Credentials Flow for a website that authorizes as the site itself might not be the safest approach for web apps. This is because storing the clientId and secret in the browser could expose them to potential theft and misuse. Furthermore, adhering to best practices such as rotating these credentials could become challenging, as they might be present in multiple browsers.

In essence, following what Okka [said](https://auth0.com/docs/get-started/authentication-and-authorization-flow/which-oauth-2-0-flow-should-i-use)  a web app can be viewed as a user-friendly interface for interacting with APIs and the data they provide. The individual, or Resource Owner, utilizes a Client (web app) acting on their behalf in a User Agent (browser) to access the ODA Component OpenAPI (Resource Server).

**Comment by gjo-satec** [comment]
Nowhere is stated how to configure the API Gateway with the right roles and resources if someone decide to add the security checks on that point
a new operator? Maybe implement TMF672 UserRole in the Component to feed the Permission and Resources into the API Gateway
I can think of several scenarios

- API Gateway not checking anything just doing routing
- API Gateway just checking Authentication, checking that the token presented is valid
- API Gateway doing a full authorization

**Comment by LesterThomas** [comment]
> On UC001 Secrets - Identity
> 
> * Create and assign a role specifically to access the secret for the deployment/statefulset
> * Mutating operator for dynamically adding the secret.
> * Rotate Secrets
> * If aiming for zero security we should aim for encryption at [rest ](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#ensure-all-secrets-are-encrypted)or even the use of Vaults
> 
> We need to clarify terms In my understanding, a role in a component may be more like a Permission, mainly about their exposed business API, along with supplemental APIs like security and configuration. Permissions are allowances for performing different operations on the resources exposed by the APIs, such as read (GET), create (POST), update (PATCH), etc. These permissions may need to be defined in advance.
> 
> I don't aim to have roles defined in the component. I don't think there's such a thing as an administrator of TMSC001; that concept has no business meaning to me. It's up to the Enterprise to decide its roles based on internal business processes. Typically, these roles will be composed of several permissions across many components. Usually, an identity will be associated with one or more of these roles. However, these roles should be managed in the IDM in a centralized manner, among other things, for security auditing.

For your four bullet points, these are all valid and we will capture these as features in the BDD to drive the design.

For the **roles versus permissions**, this is an interesting point and we should make a decision about whether a component exposes the permissions against its APIs (and allows the SRE team to group these permissions into roles appropriate for the organization), or whether a component vendor does the groupings of permissions into roles and exposes these. We have an existing issue to change from PartyRole to UserRole - before we make this change we should decide on adopting permissions vs roles. I suggest we raise it at the weekly governance call and get the perspectives of the different contributors.

**Comment by pecanpete** [comment]
Have been watching these comments with great interest as similar comment coming up as part of the work on [TMF-SF001: ODA Security: Identity and Access Management (IAM): Stage 1 and 2 Specifications (TAC-525)](https://projects.tmforum.org/wiki/pages/viewpage.action?pageId=221382600). Few observation (General comments first more specific points later) . I think we will need multiple mechanism including both OAuth 2 Authorization Code Flow. Client Credential flows The challenge is where to apply each mechanism,
- We need a clear statement of user stories use cases as there are multiple actors with different interests/needs.   SF001 added User Stories in section 5.2.1 for two  actors: 
      - An ODA Component, 
      - As a party (Operator Role/ Security Role) Day 0 Day1 Day3 use cases
      - These may not be complete 
- We need a threat assessment for each component covering the consequence of allow bad actors invoke opertins asn reuests that they should not and the privacy threat of extracting information that should not been visible or use for inappropriate processing (GDPR). 
- The ODA Security and Privacy team has published prior work [IG1187 ODA Enterprise Risk Assessment v2.0.0](https://www.tmforum.org/resources/standard/ig1187-oda-enterprise-risk-assessment-v2-0-0/) which sets out a Threat and mitigation methodology
- the ODA security and privacy team is about to start work on Zero trust impacts on ODA / ODA Components
-  It is clear that Different component have different risk profiles and  in conjunction with IG1187 and a set of mechanism identified in ODA CA that we need a ODA component security assessment checklist so component designers can select the correct mechanism to mitigate specific component risks
Catalyst proposal  ODA COMPASS (Component privacy and security) zero trust was intended to address the need for checklists.
[ will put the specific in the next post as this is getting to TLDR]

**Comment by pecanpete** [comment]
Detailed comments

We need to support both something pragmatic for the the lab to support testing but also  need the lab to investigate the options for Security mechanisms and where to apply 

- >Roles permissions  UC001 Currently I understand that the proposal is that the individual components define the roles that can access them and the associated permissions including access to attribute for GDPR purpooses. rles can be asociae with people and devices /app/components. This makes sense as only the component designer is going to know what roles make sense to it ( i.e. set of roles might be different for each component based on what it does . For example looking at the product catalog 41 functions only  a few ~4 are to do with browsing and searching  the catalog, the rest are administering and managing Product specifications and their lifecycle, analytics, security roles, etc. 
- >Secrets UC003 Comments  are good nd getting lab input on what mechanism might be used would be good outcome. This also came up as a candidate best practice guide for the ODA Sec and Privacy team to support zero trust. 
- > UC007 the Zero trust work in ODA Sec shows we will need encryption between component ( there are a few industry guidebooks for Kubernetes that make this point. Service mesh is one way of centralising the required interconnections permission and dependencies ( for components )  that than doing pair wise for component ( Not this might mean stating that client credential flow is not prefeed approach in a k8S solution .  Passthrough is about Authorisation Code Flow to support ultimately a human uses . think Oauth 2 relying Party entity has a model that can be applied here.
- > Side note in putting together SFO1 https://projects.tmforum.org/wiki/pages/viewpage.action?pageId=221382600 I had to reverse engineer earlier version of these ODACA use case to explicitly show relationship to Oauth 2 entities and whether they are are hosted in the Component or the canvas. I plan to update these reverse engineered material to align with revised ODAACA UC sequence charts,
- UC007 Browser Secrets - good point  However I thought Authorization Code Flow is intended to alleviate that need so we probably ned to go to a deeper level of analysis.
- API Gateway  In zero trust the notion is to enforce at every component however in current practise API Gateways are also used to define static perimeters. Likely we need some deeper analysis on API gateway security functionality as we probably have to support legacy approaches whilst moving to Zero trust ( to minimise lateral movement) . We did get an interesting proposal from DT in the ODA Sec & Privacy team about Zero trust and legacy applications which we may propose s a best practice. I suspect that we'll need to cover all three of the options identified by Gustavo.

**Comment by peeterko2** [comment]
> > On UC001 Secrets - Identity
> > 
> > * Create and assign a role specifically to access the secret for the deployment/statefulset
> > * Mutating operator for dynamically adding the secret.
> > * Rotate Secrets
> > * If aiming for zero security we should aim for encryption at [rest ](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#ensure-all-secrets-are-encrypted)or even the use of Vaults
> > 
> > We need to clarify terms In my understanding, a role in a component may be more like a Permission, mainly about their exposed business API, along with supplemental APIs like security and configuration. Permissions are allowances for performing different operations on the resources exposed by the APIs, such as read (GET), create (POST), update (PATCH), etc. These permissions may need to be defined in advance.
> > I don't aim to have roles defined in the component. I don't think there's such a thing as an administrator of TMSC001; that concept has no business meaning to me. It's up to the Enterprise to decide its roles based on internal business processes. Typically, these roles will be composed of several permissions across many components. Usually, an identity will be associated with one or more of these roles. However, these roles should be managed in the IDM in a centralized manner, among other things, for security auditing.
> 
> For your four bullet points, these are all valid and we will capture these as features in the BDD to drive the design.
> 
> For the **roles versus permissions**, this is an interesting point and we should make a decision about whether a component exposes the permissions against its APIs (and allows the SRE team to group these permissions into roles appropriate for the organization), or whether a component vendor does the groupings of permissions into roles and exposes these. We have an existing issue to change from PartyRole to UserRole - before we make this change we should decide on adopting permissions vs roles. I suggest we raise it at the weekly governance call and get the perspectives of the different contributors.

I believe it is important that we align on the terminologies used for a correct understanding.
Based on TMF672:

- **Entitlement**: a particular action allowed for a particular function
- **UserRole**: A collection of entitlements (exposed by a component?)
- **Permission**: Given by an individual (granter) to another individual (user) to get access to a set of his owned manageable assets

In my understanding this means that a component doesn't have to be forced to expose fine grained entitlements on each managable asset. But instead can group a number of these entitlements in a UserRole. These UserRoles can be used for  RBAC (Role Based Access Control). Permissions are then maintained in the canvas (Keycloak) were an "ODA Admin" grants a Permission to an individual or to another Component.
This is my first attempt at mapping the TMF entities on Keycloak functionality.

**Comment by gjo-satec** [comment]
Maybe some of our problems is trying to use our ODA flavour terminology for a domain that has its own (and one complicated)

Keycloak uses permission[ almost as synonymous of entitlement](https://wjw465150.gitbooks.io/keycloak-documentation/content/authorization_services/topics/service/entitlement/entitlement-api-aapi.html)

Splitting the role Authorization Server in OAUTH2 between Keycloak (for example) and the ODA component(that it's already the Resource Server), that sharing of responsibilities could lead to inconsistencies, we wider the attack surface, we have n(components)+1 implementations of a Resource Server using different tech stacks so that a vulnerability may compromise the whole.

Having said that, I'm far from being an expert in the field and understanding its subtleties.
Maybe it'll end up being some Byzantine discussion because of the meaning of the words. We would need specialized advice on the field and then try to find the best way to fit our terminology/APIs into that.

**Comment by peeterko2** [comment]
The difficulty with security is that we will need to allign existing TM Forum concepts with security concepts from OAuth.
Here is a first attempt based on David's figure 1 in (SFO01 https://projects.tmforum.org/wiki/pages/viewpage.action?pageId=221382600)

- Authorisation **Resource Server**: This is the OAuth name for the Core Function of an ODA component. 
- Authorisation **Resource Owner**: This is by definition a Party. Therefore it doesn't really seem to be part of the component. In my interpretation this seems to be the Data Owner of an entity as defined in Data governance principles. It is the party that decide who gets permission to act on an entity. That would mean that the permission is what is documented in keycloak and as such the Resource Owner belongs more to the Canvas in my view.
- Authorisation **Role Definition**: Roles are defined in the Security Function of the ODA component. UC001 describes the communication of these roles to canvas. The roles that are being defined seem more alligned to linux groups than to Business role represented by PartyRoles.The puml diagram for UC001 should use UserRole instead of PartyRole. 
- Authorisation **Policy Enforcement Point (PEP)**: This is the Security Function that protects the Resource Server. It acts on a JWT-token received with a OpenAPI request that contains a set of claims. For a RBAC (Role Based Access Control) one of the claims should contain the UserRole given to the canvas. ODA-CA needs to take a decision on which claim contains this information. The JWT-token will typically also have claims for the client application (calling component) and the relying party. In case of RBAC these would be used for auditing purposes (and should be documented in the Notifications generated by the component)

**Comment by pecanpete** [comment]
Koen Agree mostly with you observations. Would note that exactly where the resource server is depends a bit on where the trust boundaries are set; and these are different for current network perimeter based solution and Zero Trust (ZT) solution which are likely to be closer to the individual components of K8S cluster level.  Given the proposition for ZT is risk based control the answer might be different for different components e.g those with PII and those without. IMHO we need a checklists for component and canvas designers with recommendation on what mechanisms should be selected based on risk assessment. However for ODA CA exploring the option and identifying the pro and cons ( complexity computational intensity etc ) would be a valuable outcome.

**Comment by pecanpete** [comment]
Just a note on updates to https://projects.tmforum.org/wiki/pages/viewpage.action?pageId=221382600)  I updated teh ODACA UC001 and UC003 scenarios to align with what has been posted here as of 12 April 2023 . I have material to add UCC007 and UC008 into SF01 once I get a a clear hour to edit it. Note SF 001 tries to relate these ODA-CA implementation oriented sequences  to OAUTH Entities/Roles as per Koen's observation above. It has  has a first pass at the security services that have to be exposed between those Oauth entities which will allow us to document features for the BDD

**Comment by gjo-satec** [comment]
I am sharing some thoughts about the current implementation. Now, through a security operator, different components create a client within a realm and create roles for that component within the client. That means there will be N clients if there are N components.
Assuming that various users (human or not) are already registered in Keycloak (either directly or federated with an external system like Active Directory), this approach has several issues:

1. **Multiple credentials:** If component X needs to access component Y, it must be provided with credentials for the associated client Y. If it needs to access component Z, it also needs credentials for client Z. More dependencies lead to more credentials.

1. **Roles and permissions restrictions**: Roles and permissions in Keycloak clients are restricted to that specific client. There are ways to bypass this, such as using role_mappers to customize roles, but this requires coding and managing component additions and removals and is not considered a best practice due to potential security issues.

1. **Token exchange: T**okens could be exchanged based on the proposed standard RFC 8693 OAuth 2.0 Token Exchange. However, the component must know the target client, which adds complexity to the implementation.

1. **Latency issues**: Regardless of the chosen solution, latency problems may arise due to multiple re-authentications required in requests.

1. **Role and permission modifications:** Allowing roles and permissions to be modified at the component level implies a need for synchronization with Keycloak. Adding more concerns to the security operator

1. **Human users:** The situation may be worse for human users using the authorization flow due to multiple re-authentications.

That leads to a scenario where we have to do probably too many things on the security operator or hand over too many unrelated pieces to the human operator expecting him to figure out how to set it all up.

**Comment by pecanpete** [comment]
Gustavo some  good points. A few other considerations. 

- Current practice of physical Network perimeter security using  API gateway between red and Green Zone is known to be poor at inhibiting lateral movement of malicious actors once in the green Zone. 

- At the  other end Zero trust suggest 'never trust always verify' whcih implies for ODA  every component has to be secured  and all access verified at the per component level . This encounters all the scaling points that you identify. 

- HOWEVER increasingly Governments are apply pressure and regulation to adopt zero trust principles ( In UK this is already in law, and other territories such as US Canada and Australia are going down this is path too.  

- This suggest that an API gateway might protect a group or zone  of ODA component( Including case of  just one). 

- The level of granularity can only be decided  by a risk assessment of impact of lateral movement  between the ODA components in such a zone.  The ODA Security And Privacy project has some  work on Enterprise risk assessment IG1187 of ODA components. 

- IMHO architecturally this means we need to support IAM mechanism that can be applied to either single ODA component or small groups/zones of ODA component. The design need to be done on a risk assessment balanced against the implementations cost such as you mention . Looking at some of the regulation there will be cases where individual component need to be secure.

- On the point Role and permission modifications: Allowing roles and permissions to be modified at the component level implies a need for synchronization with Keycloak. My understanding of the proposal is that each component has an API that can provide all the roles recognised by the Component ( we'll need to live with Roles and permissions in Keycloak clients are restricted to that specific client for the moment). 

- What would help is to document design and implementions checklists to help designers and implementer work out the balance between verifying at component level - which IMHO would be the default stance - and relaxing to group/ Zone of components based on a systematic risk assessment of lateral movement.

**Comment by gjo-satec** [comment]
I agree mostly (if not all) with you, Dave. A few more thoughts:

- Increasingly, we are going to be under pressure of more and more security regulations, not just for PII regulation but for being part of the set of critical infrastructures that every government is worried about
- None of the balances between convenience and stringent security come without a cost.
- I tend to think that we have to restrict Canvas role to feed whatever is going to do the dirty duty and set up the pipelines correctly, e.g. ensuring that every actor has the right configuration, all the connections are done through TLS providing certificates, and so
- I think no commercial solution for identity management such as Keycloak, Okka  is going to fulfil our requirements just with configuration, but my knowledge in this field is limited, and I hope to be surprised
- Getting to a security solution that comes out in an emergent way from the aggregation of  security of (interchangeable) components or groups/zones of  them, with dependencies among themselves, It will be a tough challenge
-  So probably we should try to focus on an absurdly minimal MVP, learn in the process and iterate

**Comment by 249043822** [comment]
Hi, I have some questions about the security apis for oda on UC001 and UC008..., can anyone help me? 
1. UC001 said that the bootstrap process of canvas will create a system user for component to call other apis, how to get this user&password for the component? how to assign roles for this user?
2.  The security operator will sync roles to IAM from PartyRole API, who created these roles  and who will use these roles? I could not find these roles assigned to users in canvas
thanks

**Comment by pecanpete** [comment]
We have curated some of this  ODA CA work in to a draft ODA Canvas service at the logical level  see IG1330 at  https://projects.tmforum.org/wiki/pages/viewpage.action?pageId=256319200 
We are in the next sprint planning to address the concrete stage 3 API specifications

- Item#1 work  by Ferenc Heckler is looking at Kubernetes secrets. Thread is at https://github.com/tmforum-oda/oda-canvas/pull/83/files/96aa40044088dac7671993a8284dc8d7ef5aee6d..2a818dafcf0c41450d674fda2ccbd584496b722f   

- Item#2 The design of ODA component should define the roles they recognise and put them the component  YAML metadata and behind a User Roles and permissions Service such as being implemented in  TMF672 (User) roles and permissions API . Note we need identities not just  for parties but devices and ODA components for which different OAuth2 Flows are required.
- You might also wan to look at the draft work on Digital Identityhttps://projects.tmforum.org/wiki/display/AP/TMFXXX+Digital+Identity+Access+Control+API+Suite+Profile+v1.0.0

**Comment by LesterThomas** [comment]
Closing this issue as it was only to capture input into Authentication
